CRM/Controllers/LeadController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using CRM.Business.Dtoes.CampaignDtoes;
using CRM.Business.Dtoes.City;
using CRM.Business.Dtoes.MemberDtoes;
using CRM.Core.Entities.City;
using CRM.Core.Entities.Currency;
using CRM.Core.Entities.District;
using CRM.Core.Entities.Industry;
using CRM.Core.Entities.Lead;
using CRM.Core.Entities.Manufacturer;
using CRM.Core.Entities.Member;
using CRM.Core.Entities.Product;
using CRM.Core.Entities.Unit;
using CRM.Core.Entities.Vendor;
using CRM.Data.Repository.CrmRepository;
using CRM.Data.Repository.CustomerRepository;
using CRM.Data.Repository.LeadRepository;
using CRM.Data.Repository.ProductRepository;
using DevExpress.Office.Utils;
using DevExpress.Web.Mvc;

namespace CRM.Controllers
{
    public class LeadController : Controller
    {
        #region prop
        /// <summary>
        /// The _repository
        /// </summary>
        private ILeadRepository _repository;

        /// <summary>
        /// The model
        /// </summary>
        private IQueryable<Crm_Lead> model;
        #endregion

        public LeadController(ILeadRepository repository)
        {
            this._repository = repository;
        }

        /// <summary>
        /// Users this instance.
        /// </summary>
        /// <returns></returns>
        [Authorize(Order = 1)]
        public ActionResult Leads()
        {
            return View();
        }

        public ActionResult LeadsNewForm()
        {
            model = _repository.GetAllLead();


            var crmLead = model.FirstOrDefault();
            if (crmLead != null)
            {
                var leadSources = crmLead.Crm_LeadSource;
                ViewData["Crm_LeadSource"] = leadSources;
                Session["Crm_LeadSource"] = leadSources;

                var leadStatu = crmLead.Crm_LeadStatu;
                ViewData["Crm_LeadStatu"] = leadStatu;
                Session["Crm_LeadStatu"] = leadStatu;

                var industry = crmLead.This_Industry;
                ViewData["This_Industry"] = industry;
                Session["This_Industry"] = industry;
            }

            var createPermissions = ConfigurationManager.AppSettings["CreatePermissions"];
            var firstOrDefault = model.FirstOrDefault();
            ViewData["IsAuthorized"] = firstOrDefault != null && createPermissions.Contains(firstOrDefault.CurrentRole);

            if (model == null)
            {
                return RedirectToAction("Index", "Login");
            }

            return View(new Crm_Lead());
        }

        public ActionResult TabPageTest()
        {
            model = _repository.GetAllLead();


            var crmLead = model.FirstOrDefault();
            if (crmLead != null)
            {
                var leadSources = crmLead.Crm_LeadSource;
                ViewData["Crm_LeadSource"] = leadSources;
                Session["Crm_LeadSource"] = leadSources;

                var leadStatu = crmLead.Crm_LeadStatu;
                ViewData["Crm_LeadStatu"] = leadStatu;
                Session["Crm_LeadStatu"] = leadStatu;

                var industry = crmLead.This_Industry;
                ViewData["This_Industry"] = industry;
                Session["This_Industry"] = industry;
            }

            var createPermissions = ConfigurationManager.AppSettings["CreatePermissions"];
            var firstOrDefault = model.FirstOrDefault();
            ViewData["IsAuthorized"] = firstOrDefault != null && createPermissions.Contains(firstOrDefault.CurrentRole);

            if (model == null)
            {
                return RedirectToAction("Index", "Login");
            }

            return View(new Crm_Lead());
        }

        public ActionResult TabPage()
        {
            model = _repository.GetAllLead();


            var crmLead = model.FirstOrDefault();
            if (crmLead != null)
            {
                var leadSources = crmLead.Crm_LeadSource;
                ViewData["Crm_LeadSource"] = leadSources;
                Session["Crm_LeadSource"] = leadSources;

                var leadStatu = crmLead.Crm_LeadStatu;
                ViewData["Crm_LeadStatu"] = leadStatu;
                Session["Crm_LeadStatu"] = leadStatu;

                var industry = crmLead.This_Industry;
                ViewData["This_Industry"] = industry;
                Session["This_Industry"] = industry;
            }

            var createPermissions = ConfigurationManager.AppSettings["CreatePermissions"];
            var firstOrDefault = model.FirstOrDefault();
            ViewData["IsAuthorized"] = firstOrDefault != null && createPermissions.Contains(firstOrDefault.CurrentRole);

            if (model == null)
            {
                return RedirectToAction("Index", "Login");
            }

            return View(new Crm_Lead());
        }

        /// <summary>
        /// Users the grid view partial.
        /// </summary>
        /// <returns></returns>
        [ValidateInput(false)]
        public ActionResult GridViewPartial()
        {
            model = _repository.GetAllLead();

            
            var crmLead = model.FirstOrDefault();
            if (crmLead != null)
            {
                var leadSources = crmLead.Crm_LeadSource;
                ViewData["Crm_LeadSource"] = leadSources;
                Session["Crm_LeadSource"] = leadSources;

                var leadStatu = crmLead.Crm_LeadStatu;
                ViewData["Crm_LeadStatu"] = leadStatu;
                Session["Crm_LeadStatu"] = leadStatu;

                var industry = crmLead.This_Industry;
                ViewData["This_Industry"] = industry;
                Session["This_Industry"] = industry;

                foreach (var item in model)
                {
                    var leadSource = leadSources.FirstOrDefault(t => t.LeadSourceId == item.LeadSourceId);
                    if (leadSource != null)
                    {
                        item.LeadSourceNameId = leadSource.Description;
                    }

                    var statu = leadStatu.FirstOrDefault(t => t.LeadStatusId == item.LeadStatusId);
                    if (statu != null)
                    {
                        item.LeadStatuNameId = statu.Description;
                    }

                    var thisIndustry = industry.FirstOrDefault(c => c.IndustryId == item.IndustryId);
                    if (thisIndustry != null)
                    {
                        item.IndustryNameId = thisIndustry.Description;
                    }
                }
            }

            var createPermissions = ConfigurationManager.AppSettings["CreatePermissions"];
            var firstOrDefault = model.FirstOrDefault();
            ViewData["IsAuthorized"] = firstOrDefault != null && createPermissions.Contains(firstOrDefault.CurrentRole);

            if (model == null)
            {
                return RedirectToAction("Index", "Login");
            }

            return PartialView("_LeadGridViewPartial", model.OrderByDescending(x => x.LeadId).ToList());
        }

        /// <summary>
        /// Grids the view partial add new.
        /// </summary>
        /// <param name="param">The parameter.</param>
        /// <param name="selectedIDsHF">The selected i ds hf.</param>
        /// <returns></returns>
        [HttpPost, ValidateInput(false)]
        public ActionResult GridViewPartialAddNew([ModelBinder(typeof(DevExpressEditorsBinder))] Crm_Lead param)
         {
             string value = EditorExtension.GetValue<string>("ProductName");
             param.IsActive = true;
            _repository.SaveLead(param);

            return View("Leads");

        }

        /// <summary>
        /// Bulks the edit.
        /// </summary>
        /// <param name="param">The parameter.</param>
        /// <returns></returns>
         [HttpPost, ValidateInput(false)]
        public ActionResult BulkEdit([ModelBinder(typeof(DevExpressEditorsBinder))] Crm_Lead param)
        {
            var result = param.CurrentOperation.Split(',');
            if (result[0] == "Edit")
            {
                 var allLeads = _repository.GetAllLead();

                for (int i = 1; i <= result.Length-1; i++)
                {
                    var lead = allLeads.FirstOrDefault(l => l.LeadId == int.Parse(result[i]));
                    if (lead != null)
                    {
                        lead.AnnualRevenue = param.AnnualRevenue != 0 ? param.AnnualRevenue : lead.AnnualRevenue;
                        lead.AssignedTo = param.AssignedTo != 0 ? param.AssignedTo : lead.AssignedTo;
                        lead.CityId = param.CityId;
                        lead.Company = param.Company ?? lead.Company;
                        lead.Description = param.Description ?? lead.Description;
                        lead.Designation = param.Designation ?? lead.Designation;
                        lead.DistrictId = param.DistrictId;
                        lead.EmailOptOut = param.EmailOptOut;
                        lead.Fax = param.Fax ?? lead.Fax;
                        lead.FirstName = param.FirstName ?? lead.FirstName;
                        lead.IndustryId = param.IndustryId;
                        lead.LastName = param.LastName ?? lead.LastName;
                        lead.LeadSourceId = param.LeadSourceId;
                        lead.LeadStatusId = param.LeadStatusId;
                        lead.MobilePhone = param.MobilePhone ?? lead.MobilePhone;
                        lead.NumberEmployees = param.NumberEmployees != 0 ? param.NumberEmployees : lead.NumberEmployees;
                        lead.POBox = param.POBox ?? lead.POBox;
                        lead.PostalCode = param.PostalCode ?? lead.PostalCode;
                        lead.PrimaryEmail = param.PrimaryEmail ?? lead.PrimaryEmail;

CRM/Views/Vendor/AssignToPartial.cshtml
@model CRM.Core.Entities.Vendor.Crm_Vendor
@Html.DevExpress().ComboBox(settings => {
    settings.Name = "AssignedTo";
        settings.CallbackRouteValues = new { Controller = "Vendor", Action = "AssignToPartial" };
        settings.Properties.ValueType = typeof(int);
        settings.Properties.TextField = "UserName";
        settings.Properties.ValueField = "UserId";
        settings.Properties.EnableCallbackMode = true;
        settings.Properties.CallbackPageSize = 20;
        settings.ControlStyle.CssClass = "form-control";
         settings.Width = 177;
        settings.ShowModelErrors = true;
}).BindList(CRM.Models.User.GetCrmUserDto()).Bind(Model.AssignedTo).GetHtml()

CRM/Views/Vendor/CityPartial.cshtml
@model CRM.Core.Entities.Vendor.Crm_Vendor
@Html.DevExpress().ComboBox(settings => {
        settings.Name = "State";
        settings.CallbackRouteValues = new { Controller = "Vendor", Action = "CityPartial" };
        settings.Properties.ValueType = typeof(int);
        settings.Properties.TextField = "DistrictName";
        settings.Properties.ValueField = "DistrictId";
        settings.Properties.EnableCallbackMode = true;
        settings.Properties.CallbackPageSize = 20;
        settings.ShowModelErrors = true;
        settings.Properties.ClientSideEvents.BeginCallback = "function(s, e) { e.customArgs['CityId'] = CityId.GetValue(); }";
        settings.ControlStyle.CssClass = "form-control";
        settings.Width = 177;
        settings.ShowModelErrors = true;
}).BindList(CRM.Models.City.GetCities(Model.CityId)).Bind(Model.State).GetHtml()

CRM/Views/Vendor/CountryPartial.cshtml
@model CRM.Core.Entities.Vendor.Crm_Vendor

@Html.DevExpress().ComboBox(settings => {
        settings.Name = "CityId";
        settings.CallbackRouteValues = new { Controller = "Vendor", Action = "CountryPartial" };
        settings.Properties.ValueType = typeof(int);
        settings.Properties.TextField = "Name";
        settings.Properties.ValueField = "Code";
        settings.Properties.EnableCallbackMode = true;
        settings.Properties.CallbackPageSize = 20;
        settings.ShowModelErrors = true;
        settings.Properties.ClientSideEvents.SelectedIndexChanged = "function(s, e) { State.PerformCallback(); }";
        settings.ControlStyle.CssClass = "form-control";
        settings.Width = 177;
        settings.ShowModelErrors = true;
}).BindList(CRM.Models.Country.GetCountries()).Bind(Model.CityId).GetHtml()  

CRM/Views/Vendor/GLAccountPartial.cshtml
@model CRM.Core.Entities.Vendor.Crm_Vendor
@Html.DevExpress().ComboBox(settings => {
        settings.Name = "GLAccount";
        settings.CallbackRouteValues = new { Controller = "Vendor", Action = "GLAccountPartial" };
        settings.Properties.ValueType = typeof(int);
        settings.Properties.TextField = "Name";
        settings.Properties.ValueField = "GLAccountId";
        settings.Properties.EnableCallbackMode = true;
        settings.Properties.CallbackPageSize = 20;
        settings.ShowModelErrors = true;
        settings.ControlStyle.CssClass = "form-control";
        settings.Width = 177;
        settings.ShowModelErrors = true;
}).BindList(CRM.Models.VendorModel.GetGlAccountDtos()).Bind(Model.GLAccount).GetHtml()

CRM/Views/Vendor/LoadOnDemandPartial.cshtml
@using System.Web.UI.WebControls
@using CRM.Core.Entities.Vendor


    @Html.DevExpress().PopupControl(settings =>
    {
        settings.Name = "popupControl";
        settings.CallbackRouteValues = new { Controller = "Vendor", Action = "LoadOnDemandPartial" };
        settings.CloseAction = CloseAction.OuterMouseClick;
        settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
        settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
        settings.ShowFooter = true;
        settings.AllowDragging = true;
        settings.EnableHotTrack = true;
        settings.Height = Unit.Pixel(130);
        settings.Width = Unit.Pixel(920);
        settings.LoadContentViaCallback = LoadContentViaCallback.OnFirstShow;
        settings.PopupElementID = "ShowButton";
        settings.HeaderText = "Updatable content";
        settings.ClientSideEvents.CloseUp = "function(s, e) {  GridView.UnselectRows(); GridView.Refresh();  }";

        settings.SetContent(() => {
                                      Html.RenderPartial("TabPage", new Crm_Vendor());
        });

        settings.SetFooterTemplateContent(c =>
        {
            Html.RenderPartial("TabPageFooter");
            @Html.DevExpress().TextBox(s => {
                s.Name = "ProductName";
                s.ClientVisible = false;
            }).GetHtml();
            //ViewContext.Writer.Write("<div style=\"overflow: hidden\"> <div style=\"padding: 26px; float right;\">");
            //ViewContext.Writer.Write("<div class=\"pull-right box-tools\"> <button class=\"btn btn-info btn-sm\" data-widget='collapse' data-toggle=\"tooltip\" title=\"Collapse\"><i class=\"fa fa-plus\"></i>Save</button><button type=\"button\" onclick=\"@(\"window.location.href='" + @Url.Action("Leads", "Lead") + "'\");\" class=\"btn btn-info btn-sm\" data-widget='remove' data-toggle=\"tooltip\" title=\"Remove\"><i class=\"fa fa-times\"></i>Cancel</button></div><!-- /. tools -->");
            //ViewContext.Writer.Write("</div></div>");
        });
    }).GetHtml()

CRM/Views/Vendor/TabPageAddressInformation.cshtml
@model CRM.Core.Entities.Vendor.Crm_Vendor
<script type="text/javascript">
    function PostEditForm() {

        SelectedId();
        var data = {
            param: $(this).serialize()
        };

        $.ajax({
            url: "/Vendor/GridViewPartialAddNew",
            type: "POST",
            dataType: "json",
            contentType: 'application/json',
            data: JSON.stringify(data)
        });
    }
</script>
@*@using (Html.BeginForm("GridViewPartialAddNew", "Lead", FormMethod.Post, new {id = "frmTab"}))
{*@
    <section class="content">
    <div class='row'>
        <div class='col-md-12'>
            <div class='box box-danger'>
                <div class='box-header'>
                    <h3 class='box-title'>Address Information<small></small></h3>
                    <!-- tools box -->
                    <div class="pull-right box-tools">
                    </div><!-- /. tools -->
                </div><!-- /.box-header -->
                <div class='box-body pad'>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <label style="width: 145px; height: 10px;">Street: </label>
                                </div>
                                @Html.DevExpress().TextBox(s =>
                                    {
                                        s.Name = "Street";
                                        s.ShowModelErrors = true;
                                        s.ControlStyle.CssClass = "form-control";

                                    }).Bind(Model.Street).GetHtml()
                            </div><!-- /.input group -->
                        </div>
                        <div class="col-md-6 form-group">
                            <div class="form-group">

                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <label style="width: 145px;">PO Box:</label>
                                    </div>
                                    @Html.DevExpress().TextBox(s =>
                                        {
                                            s.Name = "POBox";
                                            s.ShowModelErrors = true;
                                            s.ControlStyle.CssClass = "form-control";

                                        }).Bind(Model.POBox).GetHtml()
                                </div><!-- /.input group -->
                            </div><!-- /.form group -->
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <label style="width: 140px;">City:</label>
                                    </div>
                                    @Html.Partial("CountryPartial", Model)
                                    @*<input type="text" class="form-control" data-inputmask='"mask": "(999) 999-9999"' data-mask />*@
                                </div><!-- /.input group -->
                            </div><!-- /.form group -->
                        </div>
                        <div class="col-md-6 form-group">
                            <div class="form-group">

                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <label style="width: 140px;">District:</label>
                                    </div>
                                    @Html.Partial("CityPartial", Model)
                                </div><!-- /.input group -->
                            </div><!-- /.form group -->
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <label style="width: 140px;">Postal Code:</label>
                                    </div>
                                    @Html.DevExpress().TextBox(s =>
                                        {
                                            s.Name = "PostalCode";
                                            s.ShowModelErrors = true;
                                            s.ControlStyle.CssClass = "form-control";

                                        }).Bind(Model.PostalCode).GetHtml()
                                    @*<input type="text" class="form-control" data-inputmask='"mask": "(999) 999-9999"' data-mask />*@
                                </div><!-- /.input group -->
                            </div><!-- /.form group -->
                        </div>
                        <div class="col-md-6 form-group">
                            <div class="form-group">

                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <label style="width: 140px;">Country:</label>
                                    </div>
                                    @Html.DevExpress().TextBox(s =>
                                        {
                                            s.Name = "Country";
                                            s.ShowModelErrors = true;
                                            s.ControlStyle.CssClass = "form-control";

                                        }).Bind(Model.Country).GetHtml()
                                </div><!-- /.input group -->
                            </div><!-- /.form group -->
                        </div>
                    </div>
                </div>
            </div><!-- /.box -->
        </div><!-- /.col-->
    </div><!-- ./row -->
</section><!-- /.content -->
    <!-- /.content -->
@*}*@

CRM/Views/Vendor/TabPageDescriptionDetails.cshtml
@model CRM.Core.Entities.Vendor.Crm_Vendor
<script type="text/javascript">
    function PostEditForm() {

        SelectedId();
        var data = {
            param: $(this).serialize()
        };

        $.ajax({
            url: "/Vendor/GridViewPartialAddNew",
            type: "POST",
            dataType: "json",
            contentType: 'application/json',
            data: JSON.stringify(data)
        });
    }
</script>
@*@using (Html.BeginForm("GridViewPartialAddNew", "Lead", FormMethod.Post, new {id = "frmTab"}))
{*@
    <section class="content">
    <div class='row'>
        <div class='col-md-12'>
            <div class='box box-primary'>
                <div class='box-header'>
                    <h3 class='box-title'>Description Details <small></small></h3>
                    <!-- tools box -->

                </div><!-- /.box-header -->
                <div class='box-body pad'>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <div class="form-group">
                                <label>Description:</label>
                                @Html.DevExpress().Memo(
                                    settings =>
                                    {
                                        settings.Name = "Description";
                                        settings.ControlStyle.CssClass = "editor";
                                        settings.Width = 550;
                                        settings.Height = 50;

                                    }
                                    ).Bind(Model.Description).GetHtml()
                            </div><!-- /.form group -->
                        </div>
                        <div class="col-md-6 form-group">

                        </div>
                    </div>
                    
                </div>
            </div><!-- /.box -->
        </div><!-- /.col-->
    </div><!-- ./row -->
</section><!-- /.content -->
    <!-- /.content -->
@*}*@

CRM/Views/Vendor/TabPageTest.cshtml
@model CRM.Core.Entities.Vendor.Crm_Vendor
<script type="text/javascript">
    function PostEditForm() {

        SelectedId();
        var data = {
            param: $(this).serialize()
        };

        $.ajax({
            url: "/Vendor/GridViewPartialAddNew",
            type: "POST",
            dataType: "json",
            contentType: 'application/json',
            data: JSON.stringify(data)
        });
    }
</script>
@*@using (Html.BeginForm("GridViewPartialAddNew", "Lead", FormMethod.Post, new {id = "frmTab"}))
{*@
    <section class="content">
    <div class='row'>
        <div class='col-md-12'>
            <div class='box box-danger'>
                <div class='box-header'>
                    <h3 class='box-title'>Vendors Information<small></small></h3>
                    <!-- tools box -->
                    <div class="pull-right box-tools">
                        
                    </div><!-- /. tools -->
                </div><!-- /.box-header -->
                <div class='box-body pad'>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <label style="width: 160px; height: 10px;">Vendor: </label>
                                </div>
                                @Html.DevExpress().TextBox(s =>
                                {
                                    s.Name = "Name";
                                    s.ShowModelErrors = true;
                                    s.ControlStyle.CssClass = "form-control";

                                }).Bind(Model.Name).GetHtml()
                            </div><!-- /.input group -->
                        </div>
                        <div class="col-md-6 form-group">
                            <div class="form-group">

                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <label style="width: 160px;">E-Mail:</label>
                                    </div>
                                    @Html.DevExpress().TextBox(s =>
                                    {
                                        s.Name = "Email";
                                        s.ShowModelErrors = true;
                                        s.ControlStyle.CssClass = "form-control";

                                    }).Bind(Model.Email).GetHtml()
                                </div><!-- /.input group -->
                            </div><!-- /.form group -->
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <label style="width: 160px;">Phone:</label>
                                    </div>
                                    @Html.DevExpress().TextBox(
                                        settings =>
                                        {
                                            settings.Name = "OfficePhone";


                                            settings.Properties.MaskSettings.Mask = "(999) 000-00-00";
                                            settings.Properties.MaskSettings.IncludeLiterals = MaskIncludeLiteralsMode.None;
                                            settings.ControlStyle.CssClass = "form-control";
                                            settings.ShowModelErrors = true;
                                        }
                                   ).Bind(Model.Phone).GetHtml()
                                    @*<input type="text" class="form-control" data-inputmask='"mask": "(999) 999-9999"' data-mask />*@
                                </div><!-- /.input group -->
                            </div><!-- /.form group -->
                        </div>
                        <div class="col-md-6 form-group">
                            <div class="form-group">

                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <label style="width: 160px;">General Accounting No:</label>
                                    </div>
                                    @Html.Partial("GLAccountPartial", Model)
                                </div><!-- /.input group -->
                            </div><!-- /.form group -->
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <label style="width: 160px;">Website:</label>
                                    </div>
                                    @Html.DevExpress().TextBox(s =>
                                    {
                                        s.Name = "WebSite";
                                        s.ShowModelErrors = true;
                                        s.ControlStyle.CssClass = "form-control";

                                    }).Bind(Model.WebSite).GetHtml()
                                    @*<input type="text" class="form-control" data-inputmask='"mask": "(999) 999-9999"' data-mask />*@
                                </div><!-- /.input group -->
                            </div><!-- /.form group -->
                        </div>
                        <div class="col-md-6 form-group">
                            <div class="form-group">

                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <label style="width: 160px;">Category:</label>
                                    </div>
                                    @Html.DevExpress().TextBox(s =>
                                    {
                                        s.Name = "Category";
                                        s.ShowModelErrors = true;
                                        s.ControlStyle.CssClass = "form-control";

                                    }).Bind(Model.Category).GetHtml()
                                </div><!-- /.input group -->
                            </div><!-- /.form group -->
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <label style="width: 160px;">Assign To:</label>
                                    </div>
                                    @Html.Partial("AssignToPartial", Model)
                                    @*<input type="text" class="form-control" data-inputmask='"mask": "(999) 999-9999"' data-mask />*@
                                </div><!-- /.input group -->
                            </div><!-- /.form group -->
                        </div>
                    </div>
                </div>
            </div><!-- /.box -->
        </div><!-- /.col-->
    </div><!-- ./row -->
</section><!-- /.content -->
    <!-- /.content -->
@*}*@